---

- hosts: all
  become: true
  tasks:

  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install update (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:
  
    
  - name: install apache and php package for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php package for Centos
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"      

     
- hosts: db_servers
  become: true
  tasks:
  
    
  - name: install mariadb for Ubuntu
    apt:
      name: 
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb Centos
    dnf:
      name: 
        - mariadb
      state: latest
    when: ansible_distribution == "CentOS"   


- hosts: file_servers
  become: true
  tasks:
  
    
  - name: install samba 
    apt:
      package: 
        - samba
      state: latest
