---

- hosts: all
  become: true
  tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false  
    when: ansible_distribution == "CentOS"

  - name: install update (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false  
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simon
    authorized_key:
      user: simon
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH6s6OPzil9XnI8cPsOfqqwAScypX99GhBnpd3FISPyL Ansible
      "    

- hosts: web_servers
  become: true
  tasks:
  
    
  - name: install apache and php package for Ubuntu
    tags: ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php package for Centos
    tags: centos
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS" 

  - name: start httpd automatically
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"    

  - name: copy default html for site
    copy:
      src: default_sites.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644     
     
- hosts: db_servers
  become: true
  tasks:
  
    
  - name: install mariadb for Ubuntu
    tags: ubuntu
    apt:
      name: 
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb Centos
    tags: centos
    dnf:
      name: 
        - mariadb
      state: latest
    when: ansible_distribution == "CentOS"   


- hosts: file_servers
  become: true
  tasks:
  
    
  - name: install samba 
    tags: stench
    apt:
      package: 
        - samba
      state: latest
